#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/app_test_demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&characterEncoding=utf8&characterSetResults=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  redis:
#    host: localhost
#    port: 6379
#    jedis:
#      pool:
#        max-wait: 30000
#        max-active: 100
#        max-idle: 20
#        min-idle: 0
#    timeout: 3000
#    database: 1
#  cloud:
##    zipkin:
##      base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
##      discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
##    sleuth:
##      sampler:
##        probability: 1.0  #采样的百分比
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#  application:
#    name: product-server
#  zipkin:
#    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#  sleuth:
#    sampler:
#      probability: 1
#logging:
#  level:
#    com.ly.product.mapper: debug
#server:
#  port: 8700
